# 登录科大讯飞控制台-语音合成
# https://console.xfyun.cn/services/tts
# 查看自己的应用密钥
APPID:  5f9a2a59

# 看清楚, 千万别和APIKey搞反了, 不然会报错 401 Unauthorization
APISecret:  7c944666fe1f5c827f79686db1ff6c09

APIKey:  12b699e603376efd0a5ab5f01fcffdad

# 文本文件路径
text_path:  ./inputs/text_short.txt

# 长度限制，默认2000，如果超过，就自动拼接
text_limit: 2000

# 语速
speed: 80  # 0-100

# 播音员
voice_name: xiaoyan # "x2_pengfei"  # "x2_chaoge"

# 句子间换气间隔ms
sentence_sep_iter: 1000
